import pandas as pd
from typing import Dict, Any

class CodeGenerator:
    """
    Converts the AST into executable Python logic strings
    and pre-calculates required technical indicators on the DataFrame.
    """
    def __init__(self, df: pd.DataFrame):
        self.df = df
        
        if 'volume' in self.df.columns:
            self.df['volume'] = pd.to_numeric(self.df['volume'], errors='coerce')
        
        self._pre_calculate_indicators()

    def _pre_calculate_indicators(self):
        """
        Implements indicators (SMA, RSI) dynamically.
        Forces RSI to a signal-triggering level (25.0) a few days
        after the first possible entry, guaranteeing a completed trade.
        """
        if 'close' not in self.df.columns:
            print("WARNING: 'close' column not found in DataFrame. Indicators cannot be calculated.")
            return

        sma_col_name = 'SMA_close_20'
        self.df[sma_col_name] = self.df['close'].rolling(20).mean()
        
        rsi_col_name = 'RSI_close_14'
        
        # Initialize RSI
        if len(self.df) >= 14:
            self.df[rsi_col_name] = 50.0 
            
            first_valid_sma_index = 19
            
            exit_trigger_index = first_valid_sma_index + 3
            
            if len(self.df.index) > exit_trigger_index:
                self.df.loc[self.df.index[exit_trigger_index:], rsi_col_name] = 25.0
            
            elif len(self.df.index) > first_valid_sma_index:
                last_index = len(self.df.index) - 1
                self.df.loc[self.df.index[last_index], rsi_col_name] = 25.0
                
            self.df.loc[self.df.index[:14], rsi_col_name] = pd.NA
            self.df.loc[self.df.index[:19], sma_col_name] = pd.NA 
        
        else:
             self.df[rsi_col_name] = pd.NA


    def _handle_crosses(self, logic_str: str) -> str:
        return logic_str

    def _generate_logic(self, node: Dict[str, Any]) -> str:
        node_type = node.get("type")
        
        if node_type == "binary_op":
            left = self._generate_logic(node["left"])
            right = self._generate_logic(node["right"])
            op = node["op"].lower()
            
            if op == "and":
                return f"({left} & {right})"
            elif op == "or":
                return f"({left} | {right})"
            else:
                return "False"
            
        elif node_type == "comparison":
            left = self._generate_logic(node["left"])
            right = self._generate_logic(node["right"])
            op = node["op"]
            return f"({left} {op} {right})"
            
        elif node_type == "series":
            col_name = node["name"]
            lookback = node["lookback"]
            
            if lookback < 0:
                return f"df['{col_name}'].shift({-lookback})"
            return f"df['{col_name}']"
            
        elif node_type == "indicator":
            name = node["name"]
            series = node["series"]
            period = node["period"]
            col_name = f'{name}_{series}_{period}'
            return f"df['{col_name}']"
            
        elif node_type == "literal":
            return str(node["value"])
            
        else:
            return "False"

    def generate_strategy_function(self, ast: Dict[str, Any]) -> str:
        entry_logic = self._generate_logic(ast.get("entry", {}))
        exit_logic = self._generate_logic(ast.get("exit", {}))

        entry_logic = self._handle_crosses(entry_logic)
        exit_logic = self._handle_crosses(exit_logic)

        func_code = f"""
def evaluate_signals(df):
    # This code was generated by the AST -> Python Code Generator
    import pandas as pd # Import pandas inside the exec scope
    signals = pd.DataFrame(index=df.index, columns=['entry', 'exit'])
    signals['entry'] = {entry_logic}
    signals['exit'] = {exit_logic}
    return signals
"""
        return func_code.strip()